### ISSUE TITLE
Fails to compile files with non-ASCII characters in the filename.

### ISSUE THREAD

**Issue by heksesang** [VirtusLab/scala-cli#591] opened 2022-01-30 08:34 UTC
**Version(s)**

0.1.0

**Describe the bug**

With a file named `Løp.scala`, `scala-cli compile` produces the following error:
`Error: java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters`

**Expected behaviour**
The file compiles just fine.

**Comment by romanowski** [comment] 2022-01-31 10:50
Thank you @heksesang for reporting, I am able to reproduce the problem. Full stack trace is below:

```
java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: L��p.scala
  sun.nio.fs.UnixPath.encode(UnixPath.java:121)
  sun.nio.fs.UnixPath.<init>(UnixPath.java:68)
  sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:279)
  java.nio.file.Path.resolve(Path.java:515)
  os.Path.$div(Path.scala:456)
  scala.build.Inputs$ScalaFile.path$lzycompute(Inputs.scala:191)
  scala.build.Inputs$ScalaFile.path(Inputs.scala:191)
  scala.build.preprocessing.ScalaPreprocessor$stateMachine$async$1.apply(ScalaPreprocessor.scala:87)
  scala.build.EitherStateMachine.start(EitherCps.scala:58)
  scala.build.preprocessing.ScalaPreprocessor$.preprocess(ScalaPreprocessor.scala:86)
  scala.build.CrossSources$stateMachine$async$2.$anonfun$forInputs$2(CrossSources.scala:104)
  scala.collection.Iterator$$anon$11.nextCur(Iterator.scala:486)
  scala.collection.Iterator$$anon$11.hasNext(Iterator.scala:492)
  scala.collection.Iterator$SliceIterator.hasNext(Iterator.scala:268)
  scala.collection.Iterator.foreach(Iterator.scala:943)
  scala.collection.Iterator.foreach$(Iterator.scala:943)
  scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
  scala.collection.generic.Growable.$plus$plus$eq(Growable.scala:62)
  scala.collection.generic.Growable.$plus$plus$eq$(Growable.scala:53)
  scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:184)
  scala.collection.mutable.ListBuffer.$plus$plus$eq(ListBuffer.scala:47)
  scala.collection.TraversableOnce.to(TraversableOnce.scala:366)
  scala.collection.TraversableOnce.to$(TraversableOnce.scala:364)
  scala.collection.AbstractIterator.to(Iterator.scala:1431)
  scala.collection.TraversableOnce.toList(TraversableOnce.scala:350)
  scala.collection.TraversableOnce.toList$(TraversableOnce.scala:350)
  scala.collection.AbstractIterator.toList(Iterator.scala:1431)
  scala.build.CrossSources$stateMachine$async$2.$anonfun$forInputs$1(CrossSources.scala:105)
  scala.collection.immutable.List.map(List.scala:293)
  scala.build.CrossSources$stateMachine$async$2.apply(CrossSources.scala:101)
  scala.build.EitherStateMachine.start(EitherCps.scala:58)
  scala.build.CrossSources$.forInputs(CrossSources.scala:97)
  scala.build.Build$stateMachine$async$1.apply(Build.scala:146)
  scala.build.EitherStateMachine.start(EitherCps.scala:58)
  scala.build.Build$.scala$build$Build$$build(Build.scala:138)
  scala.build.Build$.$anonfun$build$6(Build.scala:407)
  scala.build.bloop.BloopServer$.withBuildServer(BloopServer.scala:250)
  scala.build.Build$.build(Build.scala:400)
  scala.build.Build$.build(Build.scala:424)
  scala.cli.commands.Run$.run(Run.scala:87)
  scala.cli.commands.Run$.run(Run.scala:25)
  scala.cli.commands.Default.run(Default.scala:38)
  scala.cli.commands.Default.run(Default.scala:10)
  caseapp.core.app.CaseApp.main(CaseApp.scala:149)
  caseapp.core.app.CommandsEntryPoint.main(CommandsEntryPoint.scala:116)
  scala.cli.ScalaCliCommands.main(ScalaCliCommands.scala:89)
  scala.cli.ScalaCli$.main0(ScalaCli.scala:148)
  scala.cli.ScalaCli$.main(ScalaCli.scala:71)
  scala.cli.ScalaCli.main(ScalaCli.scala)
```

**Comment by alexarchambault** [comment] 2022-01-31 11:43
I can't reproduce that, personally. All commands I can try (`scala-cli .`, `scala-cli compile .`, `scala-cli run .`, and same commands replacing `.` by `Løp.scala` or `./Løp.scala`) all work fine. That's using Scala CLI `0.1.0` on macOS.

**Comment by alexarchambault** [comment] 2022-01-31 12:09
I can reproduce from docker, with a default locale set to `US-ASCII`. What's weird though, is that [changing the locale](https://stackoverflow.com/a/28406007/3714539) works when using a JVM-based Scala CLI, but fails with a native launcher:
```bash
$ scala-cli bloop exit # just in case 
$ scala-cli . # fails
```

```bash
$ scala-cli bloop exit # just in case 
$ cs launch --jvm 16 --contrib scala-cli -r sonatype:snapshots -M scala.cli.ScalaCli -- . # works
```

**Comment by heksesang** [comment] 2022-02-01 07:33
> I can reproduce from docker, with a default locale set to `US-ASCII`. What's weird though, is that [changing the locale](https://stackoverflow.com/a/28406007/3714539) works when using a JVM-based Scala CLI, but fails with a native launcher:
> 
> ```shell
> $ scala-cli bloop exit # just in case 
> $ scala-cli . # fails
> ```
> 
> ```shell
> $ scala-cli bloop exit # just in case 
> $ cs launch --jvm 16 --contrib scala-cli -r sonatype:snapshots -M scala.cli.ScalaCli -- . # works
> ```

I now tried to launch it with coursier the same way you did, and then it works fine. My container runs en_US.UTF-8 as locale by default, but it seems that the native scala-cli launcher does not respect whatever changes I make to locale. Is ASCII hardcoded for the native launcher somehow, as part of the packaging process?

**Comment by heksesang** [comment] 2022-02-01 08:09
So it seems that using https://github.com/VirtusLab/scala-cli/releases/download/v0.1.0/scala-cli works fine, I assume that is JVM-based and is the same as running it through coursier. But https://github.com/VirtusLab/scala-cli/releases/download/v0.1.0/scala-cli-x86_64-pc-linux.gz fails, and I am then guessing this is compiled with Scala Native.

**Comment by heksesang** [comment] 2022-02-03 08:52
> I can't reproduce that, personally. All commands I can try (`scala-cli .`, `scala-cli compile .`, `scala-cli run .`, and same commands replacing `.` by `Løp.scala` or `./Løp.scala`) all work fine. That's using Scala CLI `0.1.0` on macOS.

You use the native client downloaded from the github releases in this case, by the way?

**Comment by alexarchambault** [comment] 2022-02-03 09:41
> Is ASCII hardcoded for the native launcher somehow, as part of the packaging process?

Seems it is. I'm using the launchers from the GitHub releases, yes. The binary ones are generated by GraalVM native-image.

https://github.com/VirtusLab/scala-cli/releases/download/v0.1.0/scala-cli is JVM-based on the other hand, yes.

> You use the native client downloaded from the github releases in this case, by the way?

Yes.

**Comment by alexarchambault** [comment] 2022-05-06 08:02
Should be fixed by https://github.com/VirtusLab/scala-cli/pull/966.

**Closed as completed by alexarchambault** 2022-05-06 08:02 UTC
Labels: bug
