### ISSUE TITLE
Handle directory names with spaces or explicitly reject them

### ISSUE THREAD

**Issue by charpov** [VirtusLab/scala-cli#2726] opened 2024-02-09 20:06 UTC
**Is your feature request related to a problem? Please describe.**
As a new user of `scala-cli`, I wasted time trying to debug an issue that stemmed from being in a directory with a space in its name, e.g., `Foo Bar`.

**Describe the solution you'd like**
Either handle spaces in names, or provide an error message better than:
```
Error: No project associated with Uri(file:/private/tmp/Foo%20Bar/.scala-build/?id=Foo%20Bar_103be31561)
Compilation failed
```

**Describe alternatives you've considered**
Remove the space in the name.

**Additional context**
Using file/directory names with spaces in them is a bad habit of mine, but it has helped debug many of my own scripts. ;-)

**Comment by Gedochao** [comment] 2024-02-12 09:26
Duplicate of https://github.com/VirtusLab/scala-cli/issues/2649, should be tracked there

**Closed as not planned by Gedochao** 2024-02-12 09:26 UTC
Labels: bug, duplicate
