### ISSUE TITLE
yum repo has 0.1.19; coursier/maven has stale 0.1.16

### ISSUE THREAD

**Issue by mtk** [VirtusLab/scala-cli#1713] opened 2022-12-20 15:44 UTC
the version of scala-cli currently served up by coursier/maven has 0.1.16 while the virtus lab yum repo has 0.1.19.  the coursier/maven info seems stale?

**Comment by lwronski** [comment] 2022-12-20 15:59
@mtk Thanks for reporting, I'm not able to reproduce it, when I install `scala-cli` via `cs` in docker in ubuntu I got the newest version of `scala-cli`. 
```
$ cs install scala-cli
$ scala-cli about
Scala CLI version: 0.1.19
Scala version (default): 3.2.1

```

**Comment by tgodzik** [comment] 2022-12-20 18:23
This is most likely https://github.com/coursier/coursier/issues/2603 what is your version of coursier @mtk ?

**Comment by lwronski** [comment] 2022-12-20 19:02
@mtk Can you try to use latest release of courier `v2.1.0-RC3`?  https://github.com/coursier/coursier/releases/tag/v2.1.0-RC3

In the last release of `cs`, one bug with the cache was fixed, which can cause problems like this.

**Comment by mtk** [comment] 2022-12-21 19:59
% cs install -v scala-cli
Using install directory /home/mtk/.local/share/coursier/bin
https://repo1.maven.org/maven2/io/get-coursier/apps/maven-metadata.xml
  100.0% [##########] 0B (0B / s)
Found app scala-cli in channel io.get-coursier:apps
Found prebuilt launcher at
https://github.com/VirtusLab/scala-cli/releases/download/v0.1.16/scala-cli-x86_64-pc-linux.gz
(30.8 MiB)
Wrote /home/mtk/.local/share/coursier/bin/.scala-cli.part
Wrote /home/mtk/.local/share/coursier/bin/scala-cli
Wrote /home/mtk/.local/share/coursier/bin/.scala-cli.aux
Wrote scala-cli

this is a fedora  v37 release fully up-to-date.

/mark

**Comment by mtk** [comment] 2022-12-21 20:06
sorry, responded to email and hadn't read this thread.  the v2.1.0-RC3 version fixed the problem.  thanks Tomasz and Łukasz!

**Comment by lwronski** [comment] 2022-12-22 09:19
> sorry, responded to email and hadn't read this thread. the v2.1.0-RC3 version fixed the problem. thanks Tomasz and Łukasz!

Great! So I will close this issue.

**Closed as completed by lwronski** 2022-12-22 09:19 UTC
Labels: bug
