### ISSUE TITLE
Scala-cli run command incorrectly reports Fatal invariant violated.

### ISSUE THREAD

**Issue by dasm0012** [VirtusLab/scala-cli#2829] opened 2024-03-30 15:13 UTC
**Version(s)**
Scala CLI version: 1.2.1
Scala version (default): 3.4.1
Scala 3.4.1, JVM (22)
WSL/Ubuntu

**Describe the bug**
When repeatedly executing scala-cli run command on a file that hasn't changed, scala-cli reports "Error: Fatal invariant violated: `reportEndCompilation` was called before `processEndCompilation`" - but still executes the scala file
![image](https://github.com/VirtusLab/scala-cli/assets/21970695/46b3cfdb-95e3-4a91-a762-8f142e1e8861)

**To Reproduce**
Create simple scala file (e.g. Hello World in main function)
Execute: scala-cli run ./hello.scala  => works as expected
Execute again (no changes in hello.scala file): scala-cli run ./hello.scala  => Fatal invariant is reported

**Expected behaviour**
No fatal invariant is reported

**Comment by spamegg1** [comment] 2024-03-30 17:43
I reported the same to Metals, I guess it belongs here, or to Bloop maybe?

https://github.com/scalameta/metals/issues/6266

**Comment by Gedochao** [comment] 2024-04-02 09:33
This seems to be the same issue as https://github.com/scalameta/metals/issues/6271
For now the workaround is to revert to using an older version of Bloop (`1.5.12-sc-1`)
```bash
scala-cli clean .
scala-cli --power bloop exit
scala-cli setup-ide . --bloop-version 1.5.12-sc-1
```
The issue itself is most definitely tied to Bloop and will be fixed upstream.

**Comment by spamegg1** [comment] 2024-04-02 09:38
> The issue itself is most definitely tied to Bloop and will be fixed upstream.

Shall we open an issue there? I don't see one related. Which Bloop version introduced the problem?

**Comment by Gedochao** [comment] 2024-04-02 09:50
@spamegg1 No need to introduce an issue, I think, it can be tracked here.
@tgodzik is already working on it in https://github.com/scalacenter/bloop/pull/2306
It will then need to be ported to our fork of Bloop at https://github.com/scala-cli/bloop-core
The version which introduced the problem is `1.5.16-sc-1`.

**Closed as completed** 2024-04-10 13:22 UTC
Labels: bug, Bloop

**Comment by dasm0012** [comment] 2024-04-11 19:38
Thank you for the very quick workaround + resolution :-)
