### ISSUE TITLE
Cookbook: tests with scalatest

### ISSUE THREAD

**Issue by romanowski** [VirtusLab/scala-cli#326] opened 2021-11-02 14:58 UTC
A short cookbook that will show how to define tests using ScalaTest. I should cover 2 different test files and test utils.

An example test using [Munit](https://github.com/VirtusLab/scala-cli/blob/master/examples/scalatest/MyTests.scala)

**Comment by SethTisue** [comment] 2023-06-10 03:16
duplicate of #323

**Comment by lwronski** [comment] 2023-06-11 16:33
Thanks, so I will close this issue.

**Closed as completed by lwronski** 2023-06-11 16:33 UTC
Labels: documentation, good first issue
