### ISSUE TITLE
Scala.js - package command - support for multi modules 

### ISSUE THREAD

**Issue by lwronski** [VirtusLab/scala-cli#530] opened 2022-01-07 12:54 UTC
It would be nice to support js modules in `package` command 

```
  @JSExportTopLevel(name = "onRequest", moduleID = "request_type")
  def func(...)

  @JSExportTopLevel(name = "onRequest", moduleID = "request_headers")
  def func(...)
```

for now,  `package ... --js ` throws error, that main class is missing.

**Comment by armanbilge** [comment] 2022-03-28 18:05
I started opening a new issue, but I think it's a duplicate of this one.

Besides the issue with main class missing, it's also important to be able to support multi-file output which occurs when using modules.

For example:

`test.scala`:
```scala
//> using scala "3.1.1"
//> using platform "scala-js"
//> using jsVersion "1.9.0"
//> using jsModuleKind "es"
//> using jsModuleSplitStyleStr "smallestmodules"

case class Foo(bar: String)

@main def main = println(Foo("baz"))
```

Run `scala-cli package test.scala`

output `test.js`:
```javascript
'use strict';
import * as $j_java$002elang$002eObject from "./java.lang.Object.js";
import * as $j_main$002e from "./main..js";
$j_main$002e.$s_Lmain__main__AT__V(new ($j_java$002elang$002eObject.$d_T.getArrayOf().constr)([]));
```

Notice that `test.js` references `./java.lang.Object.js` and `./main..js`; however these are not produced by scala-cli.

Multi-module support is important for integrating with modern JS tooling such as [snowpack](https://www.snowpack.dev) which enables a fast-reload development cycle.

Thanks again for all your work on improving support for Scala.js. I think solving this one will nail it.

**Comment by lwronski** [comment] 2022-03-29 09:04
Hi @armanbilge, thanks again for reporting. 

It seems, that  `java.lang.Object.js` is generated by Scala.js linker but scala-cli doesn't copy these files to the `output` directory.

I see, that Scala.js Linker generates a lot files js files, should they all be copied to the `output` directory?
```
lwronski@VL-D-0317 scala-cli-js-linking266039794926029209 % ls
Foo.js								scala.Console$.js						scala.math.Integral$.js
Hello$package$.js						scala.MatchError.js						scala.math.Numeric$.js
java.io.FilterOutputStream.js					scala.Product$$anon$1.js					scala.math.Ordered$.js
java.io.OutputStream.js						scala.Product2.js						scala.math.Ordering$.js
java.io.PrintStream.js						scala.collection.IndexedSeq.js					scala.math.ScalaNumber.js
java.lang.Character$.js						scala.collection.IterableFactory$Delegate.js			scala.package$$anon$1.js
java.lang.IllegalArgumentException.js				scala.collection.IterableOnce.js				scala.runtime.AbstractFunction0.js
java.lang.Integer$.js						scala.collection.LinearSeq.js					scala.runtime.AbstractFunction1.js
java.lang.JSConsoleBasedPrintStream$DummyOutputStream.js	scala.collection.Seq.js						scala.runtime.BoxesRunTime$.js
java.lang.JSConsoleBasedPrintStream.js				scala.collection.SeqFactory$Delegate.js				scala.runtime.IntRef.js
java.lang.NullPointerException.js				scala.collection.StrictOptimizedLinearSeqOps.js			scala.runtime.ObjectRef.js
java.lang.NumberFormatException.js				scala.collection.View.js					scala.runtime.ScalaRunTime$.js
java.lang.Object.js						scala.collection.immutable.$colon$colon$.js			scala.runtime.Statics$.js
java.lang.SecurityException.js					scala.collection.immutable.LazyList$State$Empty$.js		scala.runtime.Statics$PFMarker$.js
java.lang.StringBuilder.js					scala.collection.immutable.LazyList$State.js			scala.scalajs.runtime.AnonFunction0.js
java.lang.System$Streams$.js					scala.collection.immutable.List$$anon$1.js			scala.scalajs.runtime.AnonFunction1.js
java.lang.System$SystemProperties$.js				scala.collection.immutable.Range$.js				scala.util.CommandLineParser$.js
java.lang.UnsupportedOperationException.js			scala.collection.immutable.Stream$.js				scala.util.CommandLineParser$ParseError.js
java.lang.Utils$.js						scala.collection.immutable.VectorStatics$.js			scala.util.DynamicVariable.js
java.lang.Utils$Cache$.js					scala.collection.mutable.StringBuilder$.js			scala.util.Either$.js
java.util.Arrays$.js						scala.collection.package$$colon$plus$.js			scala.util.Left$.js
java.util.NoSuchElementException.js				scala.collection.package$$plus$colon$.js			scala.util.Right$.js
main..js							scala.math.Equiv$.js						scala.util.hashing.MurmurHash3.js
main.js								scala.math.Fractional$.js
```

I think we can do it this way. Scala-cli will require the `output` parameter to point to an existing directory, and then merge-cli will copy all files generated by the Scala.js linker into that directory.

**Comment by armanbilge** [comment] 2022-03-29 12:48
> I see, that Scala.js Linker generates a lot files js files, should they all be copied to the output directory?

Yes, that's right. But I see you've already fixed this in https://github.com/VirtusLab/scala-cli/pull/816, amazing!

**Closed as completed** 2022-03-30 11:35 UTC
Labels: bug, Scala.js
