### ISSUE TITLE
Confusing error message when providing options before command

### ISSUE THREAD

**Issue by lrytz** [VirtusLab/scala-cli#2778] opened 2024-03-06 13:09 UTC
Version 1.1.3

```
➜ sandbox scala-cli -S 3 compile A.scala
[error]  compile is not a scala-cli sub-command and it is not a valid path to an input file or directory.
```

"compile is not a scala-cli sub-command"

**Comment by SethTisue** [comment] 2024-03-06 14:59
duplicate of #2742

**Closed as not planned** 2024-03-11 09:53 UTC
Labels: bug
