### ISSUE TITLE
Weird infinte loop 

### ISSUE THREAD

**Issue by lmlynik** [VirtusLab/scala-cli#2616] opened 2023-12-07 07:27 UTC
**Version(s)**
Tested on Scala CLI 1.0.6 and 1.1.0

**Describe the bug**
On Scala 3.3.1
Running the below script creates a weird loop and the output is 
```
running
200
running
200
running
200
... and so on
```

This doesn't happen on Scala **2.13.**.
Trying on some Scala **3.2.2** doesn't compile due to diffennt issue, possibly unrelated to this issue.

This also doesn't happen in a regular SBT project.

**To Reproduce**
```scala
//> using scala 3.3.1
//> using toolkit latest
//> using dep "org.json4s::json4s-native:4.0.7"

import org.json4s._
import org.json4s.native.JsonMethods._
import org.json4s.native.Serialization
import org.json4s.native.Serialization.{read, write}

import sttp.client4.quick.*

println("running")

val request = quickRequest
  .get(uri"https://my-json-server.typicode.com/typicode/demo/posts")
  .header("Content-Type", "application/json")

val response = request
  .send()

println(response.code)

case class Post(id: Int, title: String)

implicit val formats: Formats = Serialization.formats(NoTypeHints)

val posts = read[List[Post]](response.body)

println(posts)

```
**Expected behaviour**
Scripts executes correctly and prints the posts.

**Comment by MaciejG604** [comment] 2023-12-07 08:27
It's unfortunately a known bug, a workaround is to fallback to the object wrapper with `--object-wrapper` or `//> using objectWrapper`.

Otherwise this is a duplicate of #2157, tracked under #2247 so I'll close this if there's no additional comments.

**Comment by Gedochao** [comment] 2023-12-08 09:55
Closing this as duplicate of #2157

**Closed as completed by Gedochao** 2023-12-08 09:55 UTC
Labels: bug, script-wrapper
