### ISSUE TITLE
Fix error message on //> using toolkit

### ISSUE THREAD

**Issue by szymon-rd** [VirtusLab/scala-cli#2129] opened 2023-05-19 15:09 UTC
When somebody just writes:
```
//> using toolkit
```
He is met with this error message:
```
[error]  expected 1 for the  using directive key at [...]; but got 1 values, instead.
```
Some users may find it hard to fix and understand. Please, add error like this:
```
[error] You have to provide version for the toolkit. For example, use: //> using toolkit "latest"
```

**Comment by SethTisue** [comment] 2023-05-22 19:11
maybe `//> using toolkit` should be synonymous with `//> using toolkit "latest"`?

**Comment by Gedochao** [comment] 2023-05-23 06:36
> maybe `//> using toolkit` should be synonymous with `//> using toolkit "latest"`?

@SethTisue I drafted a solution with just that in #2133, but I'm not yet sure which way we'll proceed with that 🤔

**Comment by tgodzik** [comment] 2023-05-23 08:07
Didn't we vote against leaving out `"latest"` due to the fact that it might make people overuse it and have a not reproducible script or Scala file?

**Comment by mpkocher** [comment] 2023-05-23 09:25
> Didn't we vote against leaving out `"latest"` due to the fact that it might make people overuse it and have a not reproducible script or Scala file?

Where are these discussions being held, or where are the outcomes being communicated?

**Comment by Gedochao** [comment] 2023-05-23 12:14
> Didn't we vote against leaving out `"latest"` due to the fact that it might make people overuse it and have a not reproducible script or Scala file?

Right, it seems we did and I somehow missed that part.
I'm going to change the solution to an error similar to what @szymon-rd suggested, sorry for the confusion.

**Comment by szymon-rd** [comment] 2023-05-23 12:18
> Didn't we vote against leaving out "latest" due to the fact that it might make people overuse it and have a not reproducible script or Scala file?

We did. We require writing "latest" explicitly.

@mpkocher 
The toolkit 0.2 beta will be released soon, and there will be discussion threads. Some of the decisions were made to draft the MVP of the Toolkit and present it to the community. It will be easier to discuss it that way, having the product in hand. We are purposely releasing the 0.x unstable version, so if the discussions result in some breaking changes, we can implement them. Nothing is set in stone.

**Comment by SethTisue** [comment] 2023-05-23 19:34
> Where are these discussions being held, or where are the outcomes being communicated?

Right here in this repo! (Naturally, some discussions also happen in person, but they result in pull requests in this repo, whether further discussion can happen before something is merged, and afterwards too.)

Sometimes when something is especially significant, there's a thread at https://contributors.scala-lang.org for extra visibility, for example https://contributors.scala-lang.org/t/sip-46-scala-cli-as-default-scala-command/5996

**Closed as completed** 2023-05-24 06:22 UTC
Labels: enhancement
