### ISSUE TITLE
Support test-in-src 

### ISSUE THREAD

**Issue by antholeole** [VirtusLab/scala-cli#2832] opened 2024-04-01 15:16 UTC
Hello! One feature that i'd like to have is to be able to write the source and the test in the same file - that way I can just write one off scripts without having to worry about keeping the test file next to the implementation file. 

Something like the following:

```scala
//> using test.dep org.scalameta::munit::0.7.29

object Hello {
  def main(args: Array[String]): Unit = {
    println(addOne(3))
  }

  def addOne(x: Integer) = x + 1
}

  class HelloTest extends munit.FunSuite {
    test("foo") {
      assert(Hello.addOne(3) == 4)
    }
  }
```

and then `scala-cli Hello.scala` would run `Hello.main`, while `scala-cli test Hello.scala` would run the test suite defined in `HelloTest`. Is this feasible or something that we want? I would be open to writing this feature if it's something that would be accepted. If so, I can write up a RFC-like to get some opinions on the design. Thanks!

**Comment by Gedochao** [comment] 2024-04-02 07:34
Duplicate of #1093, should be tracked there.
Closing this.

**Closed as not planned by Gedochao** 2024-04-02 07:34 UTC
Labels: duplicate, enhancement

**Comment by Gedochao** [comment] 2024-04-02 07:41
@antholeole If you are indeed interested in implementing this, let's track it in #1093.
