### ISSUE TITLE
scala-cli no longer completes command-line parameters

### ISSUE THREAD

**Issue by lucag** [VirtusLab/scala-cli#2041] opened 2023-04-17 20:48 UTC
**Version(s)**
1.0.0-RC1

**Describe the bug**
Tab completion of command-line parameters fails with the message "Failed to initialize the global options."

**To Reproduce**
1. Install the command-line completions for your shell as described in the [scala-cli documentation](https://scala-cli.virtuslab.org/docs/commands/completions/)
2. Source you shell config, or restart you shell
3. Type `scala-cli <TAB>`

**Expected behaviour**
A list (or menu) of choices for command-line options/arguments, as in previous versions of `scala-cli`

**Comment by Gedochao** [comment] 2023-04-18 06:28
Duplicate of #2001, it's already been fixed in #2004; the fix will be included in the next release

**Closed as completed by Gedochao** 2023-04-18 06:28 UTC
Labels: bug, duplicate
