### ISSUE TITLE
exclude directive does not work on Windows

### ISSUE THREAD

**Issue by hellerim** [VirtusLab/scala-cli#3181] opened 2024-09-17 01:54 UTC
**Version(s)**
1.5.0

**Describe the bug**
Excluding directories does not work on Windows 11 Enterprise (I did not check on other windows versions). When `scala-cli --exclude <dirname>` is entered on the command line or the directive `//> using exclude "dirname"`  is added to the _project.scala_ file, this results in an error when the _cli_ starts:
_Error: java.nio.file.InvalidPathException: Illegal char <*> at index 0: *_.
The only thing that works is passing the name of a single file, while globs/wildcards are ignored.

**Expected behaviour**
No error should occur. Instead, all files in the given folder should be ignored by the _scala-cli_, and globs/wildcards should be processed as usual as described in the documentation ([https://scala-cli.virtuslab.org/docs/commands/compile/#exclude-sources](https://scala-cli.virtuslab.org/docs/commands/compile/#exclude-sources)).
**Remark**
It seems that there is no way to exclude multiple directories and/or files or to pass an exclude file to the _cli_.

**Comment by Gedochao** [comment] 2024-09-18 07:29
Duplicate of #2973, let's track it there.

**Closed as not planned by Gedochao** 2024-09-18 07:29 UTC
Labels: bug, duplicate
