### ISSUE TITLE
Crash in watch mode after a few code changes

### ISSUE THREAD

**Issue by nemoo** [VirtusLab/scala-cli#3373] opened 2024-12-16 14:48 UTC
**Version(s)**

- Scala-cli 1.5.3 
- Windows 11
- Powershell

**Describe the bug**
When I run a scala-cli project in --watch mode, then after a while or after a few code (like maybe 4) changes that correctly trigger scala-cli to reload, scala-cli hangs. It does not feel deterministic to me. In that hung state, pressing ENTER does not trigger a relauch anymore.

It hangs with this error: 
```
java.lang.Exception: Timeout while waiting for buildInitialize response
  bloop.rifle.BloopServer$.buildServer(BloopServer.scala:223)
  scala.build.compiler.BloopCompilerMaker.$anonfun$1(BloopCompilerMaker.scala:48)
  scala.build.compiler.BloopCompiler.<init>(BloopCompiler.scala:15)
  scala.build.compiler.BloopCompilerMaker.$anonfun$2(BloopCompilerMaker.scala:51)
  scala.util.Try$.apply(Try.scala:217)
  scala.build.compiler.BloopCompilerMaker.create(BloopCompilerMaker.scala:51)
  scala.build.Build$.info$1$$anonfun$1(Build.scala:697)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.build.Build$.info$1(Build.scala:687)
  scala.build.Build$.run$1(Build.scala:715)
  scala.build.Build$.$anonfun$24(Build.scala:748)
  scala.build.Build$.$anonfun$adapted$1(Build.scala:748)
  scala.Function0.apply$mcV$sp(Function0.scala:42)
  scala.build.Build$Watcher.$init$$$anonfun$1(Build.scala:1274)
  java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
java.util.concurrent.TimeoutException
  java.base@17.0.6/java.util.concurrent.CompletableFuture.timedGet(CompletableFuture.java:1960)
  java.base@17.0.6/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2095)
  bloop.rifle.BloopServer$.buildServer(BloopServer.scala:220)
  scala.build.compiler.BloopCompilerMaker.$anonfun$1(BloopCompilerMaker.scala:48)
  scala.build.compiler.BloopCompiler.<init>(BloopCompiler.scala:15)
  scala.build.compiler.BloopCompilerMaker.$anonfun$2(BloopCompilerMaker.scala:51)
  scala.util.Try$.apply(Try.scala:217)
  scala.build.compiler.BloopCompilerMaker.create(BloopCompilerMaker.scala:51)
  scala.build.Build$.info$1$$anonfun$1(Build.scala:697)
  scala.build.EitherCps$Helper.apply(EitherCps.scala:19)
  scala.build.Build$.info$1(Build.scala:687)
  scala.build.Build$.run$1(Build.scala:715)
  scala.build.Build$.$anonfun$24(Build.scala:748)
  scala.build.Build$.$anonfun$adapted$1(Build.scala:748)
  scala.Function0.apply$mcV$sp(Function0.scala:42)
  scala.build.Build$Watcher.$init$$$anonfun$1(Build.scala:1274)
  java.base@17.0.6/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
  java.base@17.0.6/java.util.concurrent.FutureTask.run(FutureTask.java:264)
  java.base@17.0.6/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
  java.base@17.0.6/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
  java.base@17.0.6/java.lang.Thread.run(Thread.java:833)
  com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
  com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
```
Googling for the error did not yield any results for me.

**To Reproduce**
I have not yet tried to minimize the error. Can try to do so if needed.

**Expected behaviour**
Scala-cli should not hang when --watch mode is used.

**Comment by Gedochao** [comment] 2024-12-16 16:00
Duplicate of https://github.com/VirtusLab/scala-cli/issues/3343, already solved in https://github.com/VirtusLab/scala-cli/pull/3351.
Will be included in the next stable release.
For now, should work fine with `--cli-version nightly`.
Closing this.

**Closed as not planned by Gedochao** 2024-12-16 16:00 UTC
Labels: bug, duplicate, Bloop, --watch
