### ISSUE TITLE
Unhelpful error message on invalid source file or command

### ISSUE THREAD

**Issue by julienrf** [VirtusLab/scala-cli#1671] opened 2022-12-08 10:05 UTC
**Is your feature request related to a problem? Please describe.**

When someone runs `scala` (as installed by `cs install scala-experimental`) with an invalid command name, or an invalid source file name, the output is not helpful:

~~~ text
$ scala foobar            

[error]  foobar: not found
~~~

**Describe the solution you'd like**

The tool should explain what it tried to do (here, _running_ a Scala program named “foobar”), why it failed (here, the _file_ “foobar” does not exist), and what the user could do to fix the problem (check that the file name is correct? add a missing extension? or, in case the user simply constructed a wrong invocation, remind them that they can get general help with `scala --help`?).

**Comment by Gedochao** [comment] 2022-12-08 12:58
This is a duplicate of #1240.
Tagging #1240 as `SIP` and closing this.

**Closed as completed by Gedochao** 2022-12-08 12:58 UTC
Labels: duplicate, enhancement, SIP-46
