### ISSUE TITLE
shebang scripts fail with "assertion failed: asTerm called on not-a-Term"

### ISSUE THREAD

**Issue by SethTisue** [VirtusLab/scala-cli#451] opened 2021-12-05 21:23 UTC
on MacOS with coursier-installed scala-cli,

```
% scala-cli version
0.0.9
% cat foo.sc
#!/usr/bin/env scala-cli shebang

// using scala 3.1.1-RC1

println("hi there")
% ./foo.sc 
Compiling project (Scala 3.1.1-RC1, JVM)
Error compiling project (Scala 3.1.1-RC1, JVM)
Error: Unexpected error when compiling project_940fb43dce-4a83f2d954: 'assertion failed: asTerm called on not-a-Term val <none>'
Compilation failed
```

if I change `3.1.1-RC1` to `2.13.7` I get:

```
% ./foo.sc 
Compiling project (Scala 2.13.7, JVM)
Error compiling project (Scala 2.13.7, JVM)
Compilation failed
```

**Comment by tpasternak** [comment] 2021-12-06 11:36
Hey, unfortunately we can't reproduce it. Maybe it's a cache-releated issue. Could you try this?

```
mkdir -p /tmp/newcache
COURSIER_CACHE=/tmp/newcache ./foo.sc
```

**Comment by SethTisue** [comment] 2021-12-07 20:02
That didn't help.

Deleting `.bsp` and `.scala` didn't help.

Logging out of MacOS and back in again didn't help.

Rebooting fixed it! First run after reboot:

```
% ./foo.sc
Bloop currently running: Left(BloopNotRunning)
Starting bloop 1.4.11 on /Library/Java/JavaVirtualMachines/temurin-8.jdk/Contents/Home/bin/java
Compiling project (Scala 3.0.2, JVM)
Compiled project (Scala 3.0.2, JVM)
hi there
```

and now I'm no longer able to reproduce the problem.

**Comment by SethTisue** [comment] 2021-12-08 00:01
I probably should have tried seeing if there was a stray Bloop process around, and killing it, before resorting to logging out and/or rebooting. oh well

**Comment by tpasternak** [comment] 2021-12-31 14:17
Probably we can close this issue, please reopen it in case you see it again

**Closed as completed by tpasternak** 2021-12-31 14:17 UTC
