### ISSUE TITLE
Misleading console output for a successful publish

### ISSUE THREAD

**Issue by prolativ** [VirtusLab/scala-cli#1312] opened 2022-08-31 08:54 UTC
**Version(s)**
0.1.12

**Describe the bug**
When publishing a library, even if the publish is successful, exceptions are printed to the console:
```
Exception in thread "Thread-5" org.eclipse.jgit.errors.TranslationBundleLoadingException: Loading of translation bundle failed for [org.eclipse.jgit.internal.JGitText, en_US]
        at org.eclipse.jgit.nls.TranslationBundle.load(TranslationBundle.java:141)
        at org.eclipse.jgit.nls.GlobalBundleCache.lookupBundle(GlobalBundleCache.java:64)
        at org.eclipse.jgit.nls.NLS.get(NLS.java:125)
        at org.eclipse.jgit.nls.NLS.getBundleFor(NLS.java:101)
        at org.eclipse.jgit.internal.JGitText.get(JGitText.java:28)
        at org.eclipse.jgit.util.FS$GobblerThread.setError(FS.java:1499)
        at org.eclipse.jgit.util.FS$GobblerThread.run(FS.java:1469)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:705)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:202)
Caused by: java.util.MissingResourceException: Can't find bundle for base name org.eclipse.jgit.internal.JGitText, locale en_US
        at java.util.ResourceBundle.throwMissingResourceException(ResourceBundle.java:2045)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1683)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1586)
        at java.util.ResourceBundle.getBundle(ResourceBundle.java:1280)
        at org.eclipse.jgit.nls.TranslationBundle.load(TranslationBundle.java:138)
        ... 8 more
Caused by: java.lang.ClassCastException: org.eclipse.jgit.internal.JGitText cannot be cast to ResourceBundle
        at java.util.ResourceBundle$Control.newBundle0(ResourceBundle.java:3211)
        at java.util.ResourceBundle$Control.newBundle(ResourceBundle.java:3151)
        at java.util.ResourceBundle.loadBundle(ResourceBundle.java:1984)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1770)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.util.ResourceBundle.findBundle(ResourceBundle.java:1722)
        at java.util.ResourceBundle.getBundleImpl(ResourceBundle.java:1656)
        ... 11 more
```

Also at the end some URLs are shown so that one can check if the publish was successful, e.g.
```
 👀 Check results at
  https://oss.sonatype.org/content/repositories/public/org/virtuslab/iskra_3/0.0.2
before they land at
  https://repo1.maven.org/maven2/org/virtuslab/iskra_3/0.0.2
```
However they both don't work because they're missing a `/` at the end.

**Expected behaviour**
No exceptions shown and correct URLs

**Comment by MaciejG604** [comment] 2023-03-02 08:37
URL part has been fixed with #1535

**Comment by tgodzik** [comment] 2023-03-02 11:29
Or wait, was I too hasty closing this?

**Comment by MaciejG604** [comment] 2023-03-02 11:49
I need to give it one more check regarding the exception thrown.

**Comment by MaciejG604** [comment] 2023-03-03 11:38
I couldn't reproduce the exceptions shown above, so I suppose we can close the issue.

**Closed as completed by MaciejG604** 2023-03-03 11:38 UTC
Labels: bug, publish command
