### ISSUE TITLE
GraalVM packing fails with JVM 21

### ISSUE THREAD

**Issue by pawelprazak** [VirtusLab/scala-cli#2606] opened 2023-12-04 14:40 UTC
**Version(s)**
```
Scala CLI version: 1.1.0
Scala version (default): 3.3.1
```

**Describe the bug**
Hello world application packaging to GraalVM fails when JVM 21 is default:
```
scala-cli --power package --native-image .
```
```
Fatal error: java.lang.UnsupportedClassVersionError: org/virtuslab/besom/example/run has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0
```

It was downloading: `JVM graalvm-java17:22.3.1` but the Scala code was generated with 21.

**To Reproduce**
- JVM 21 as default
- run `scala-cli --power package --native-image .`

**Expected behaviour**
`scala-cli` should resolve bytecode version correctly when using `--native-image`

**Workaround**
Add `//> using options -java-output-version:17`

**Comment by MaciejG604** [comment] 2023-12-05 09:11
Duplicate of #2551
While `//> using options -java-output-version:17` fits the explanation and may be a good workaround.
There's a proper solution suggested in the mentioned PR.

**Closed as not planned by MaciejG604** 2023-12-05 09:11 UTC
Labels: bug, enhancement, priority: low, Community help wanted
